### PR TITLE
User Interface Mockup

### PR DESCRIPTION
**Pull request by Kasuhira**
Planned the flow of the Tic-Tac-Tow game and the interface elements

### CODE REVIEW

**Comment by redacuve** [comment]
I thought this is a mockup and it doesn't need any logic yet, because the logic is on the third milestone, but we can implement the logic on this.

**Comment by redacuve** [comment]
> ### Nice work guys   However, some requirements need to be implemented in order for us to approve this milestone. Check 
> ##### Implementation details
> * [ ]  A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
>   
>   * Instead of counting the number of moves and suddenly breaking out of the loop, you can follow the suggestion below:
> * [ ]  Inside the loop, all actions should be repeated for each player separately.
>   
>   * Only one player can be the winner.
> 
> ```ruby
> game_on = true
> 
> # initial instructions for player
> 
> while game_on
>   # loop for each move
>   
>   if winner # and/or draw (the exact condition in this milestone is not important)
>     game_on = false
>   end
> end
> ```
> 
> ### That's it  When finished, kindly resubmit another code review request 
> Happy coding 
> **_Ahmed Mahfoudh_**
@stratospherique 
I thought this is a mockup and it doesn't need any logic yet, because the logic is on the third milestone, but we can implement the logic on this.

**Comment by Kasuhira** [comment]
Hello, @stratospherique  ! How are you doing ?

Actually, since this is a Mockup we tough it wouldn't be necessary to implements such logic, are you sure we have to do this ? Because in the pathwright is like :

"The final point of this milestone is to make sure that you thought about all actions needed to play Tic Tac Toe. It does not need to work yet - this will be done in the next milestone."

Eagerly Awaiting for Your Answer.

**Comment by stratospherique** [comment]
> Hello, @stratospherique ! How are you doing ?
> 
> Actually, since this is a Mockup we tough it wouldn't be necessary to implements such logic, are you sure we have to do this ? Because in the pathwright is like :
> 
> "The final point of this milestone is to make sure that you thought about all actions needed to play Tic Tac Toe. It does not need to work yet - this will be done in the next milestone."
> 
> Eagerly Awaiting for Your Answer.

Hi @Kasuhira 

The changes that I recommended in the review are unrelated to the logic, I suggested changes that are related to:
- How to break the loop?
- Checking for the winner is done once not twice.

That's it. :pray: Contact me on slack if you need further clarifications

**Pull request merged**
